# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Homayoon (Hue) Alimohammadi (Al)"
description: > # this means to ignore newlines until "email:"
   A Hard-working, Desciplined and Motivated Software Engineer

email: homayoonalimohammadi@gmail.com
#blog logo
logo: "/assets/images/me_zoom.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/Cover.jpg"

name: 'Homayoon Alimohammadi'
author: 'Homayoon Alimohammadi'
author_image: "/assets/images/me_zoom_300_300.jpg"

paginate:	5

url: "https://homayoon.blog" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@HomayoonAlm'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/HomayoonAlm
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
    
  - icon:	github
    url:	https://github.com/HomayoonAlimohammadi
    desc:	Follow me on Github
    share_url: 
    share_title:
    share_link:

  - icon: gitlab
    url: https://gitlab.com/HomayoonAlimohammadi
    desc: Follow me on Gitlab

  - icon: linkedin
    url: https://www.linkedin.com/in/homayoon-alimohammadi/
    desc: Connect in LinkedIn